# Custom Language File for Launcher Customizer

[ejs.app]
title = "마크 놀이터"

[ejs.landing]
mediaGitHubURL = ""
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/dDj4w2PFvZ"

[ejs.settings]
sourceGithubLink = "https://github.com/mycha0216/mineplayground"
supportLink = "https://github.com/mycha0216/mineplayground/issues"

[ejs.welcome]
welcomeHeader = "마크 놀이터에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
